package com.fastcampus.kafkahandson.ugc.inspectedpost.model;

import com.fastcampus.kafkahandson.ugc.post.model.Post;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

@RequiredArgsConstructor
@Getter
public class InspectedPost {

    private final Post post;
    private final String categoryName;
    private final List<String> autoGeneratedTags;
    private final LocalDateTime inspectedAt;

    public static InspectedPost generate(
        Post post,
        String categoryName,
        List<String> autoGeneratedTags
    ) {
        return new InspectedPost(
            post,
            categoryName,
            autoGeneratedTags,
            LocalDateTime.now()
        );
    }
}