spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus?serverTimezone=Asia/Seoul
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

external-server:
  metadata:
    url: http://localhost:8088