package com.fastcampus.kafkahandson.ugc.postsearch;

import com.fastcampus.kafkahandson.ugc.inspectedpost.model.InspectedPost;
import com.fastcampus.kafkahandson.ugc.post.model.Post;

import java.time.LocalDateTime;

public class PostDocumentConverter {

    public static PostDocument toDocument(InspectedPost post) {
        return new PostDocument(
            post.getPost().getId(),
            post.getPost().getTitle(),
            post.getPost().getContent(),
            post.getCategoryName(),
            post.getAutoGeneratedTags(),
            LocalDateTime.now()
        );
    }
}
